import { AsyncStorage } from "react-native";
import { applyMiddleware, compose, createStore } from "redux";
import { persistStore, persistReducer } from "redux-persist";
import thunk from "redux-thunk";

import reducers from "../redercers";

const config = {
  key: "root",
  storage: AsyncStorage,
  blacklist: [
    // 'app',
    // 'nav',
    // 'vendor',
    // 'request',
    // 'proposal',
    // 'checklist',
    // 'checklistDetail',
    // 'maintenance',
    // 'requestCreate',
    // 'requestDetail',
    // 'notification',
    // 'servicesExtension',
    // 'servicesExtensionDetail',
    // 'servicesBasic',
    // 'servicesBasicDetail',
    // 'reportWorking',
    // 'reportGeneral',
    // 'reportGroupProgressStatus',
    // 'reportGroupProgressRating',
    // 'reportGroupProgressTimeComplete',
    // 'proposalDetail',
    // 'dashboard',
    // 'dashboardLevel2',
    // 'dashboardChecklist',
    // 'water',
    // 'waterDetail',
    // 'electric',
    // 'electricDetail',
    // 'shiftChange',
    // 'shiftChangeDetail',
    // 'shiftsChoice',
    // 'shiftsDayListChoice',
    // 'gas',
    // 'checklist_dangthuchien_khachhang',
    // 'checklist_dangthuchien',
    // 'utils',
    // 'nav',
    // 'checklisOfflinetDetail',
    // 'survey',
    // 'surveyDetail',
    // 'reportSurvey',
    "app",
    "nav",
    "vendor",
    "drawer",
    "request",
    "requestCreate",
    "requestDetail",
    "servicesExtension",
    "servicesExtensionDetail",
    "statistics",
    "servicesBasic",
    "servicesBasicDetail",
    "reportGeneral",
    "reportGroupProgressStatus",
    "reportGroupProgressRating",
    "reportGroupProgressTimeComplete",
    "home",
    "proposal",
    "checklist",
    "maintenance",
    "checklistDetail",
    "shifts",
    "shiftsDayList",
    "proposalDetail",
    "notification",
    "dashboard",
    "dashboardLevel2",
    "dashboardChecklist",
    "water",
    "waterDetail",
    "electric",
    "electricDetail",
    "shiftChange",
    "shiftChangeDetail",
    "shiftsChoice",
    "shiftsDayListChoice",
    "gas",
    "gasDetail",
    "checklist_dangthuchien_khachhang",
    "checklist_dangthuchien",
    "utils",
    "checklist_dangthuchien_taisan",
    "checklist_dangthuchien_taisan_khachhang",
    "checklist_handovermore",
    "notification_bangiao",
    "vendorHome",
    "notificationResident",
    "news",
    "requestResident",
    "vendorDetail",
    "requestCreateResident",
    "requestDetailResident",
    "feeDetail",
    "paymentHistory",
    "utilities",
    "utilitiesServices",
    "utilitiesBasicDetail",
    "utilitiesBasicBooking",
    "utilitiesServicesDetail",
    "utilitiesServicesExtension",
    "utilitiesServicesExtensionDetail",
    "fee",
    "departmentDetail",
    "utilitiesServicesBasic",
    "utilitiesServicesBasicDetail",
    "hotline",
    "badge",
    "handoverSchedule",
    "handoverScheduleDayList",
    "building",
    "survey",
    "surveyDetail",
    "reportSurvey",
    "carCard",
    "carCardCreate",
    "version",
  ],
};

export default function configureStore(onComplete) {
  const enhancers = compose(applyMiddleware(thunk));
  const persistedReducer = persistReducer(config, reducers);
  const store = createStore(persistedReducer, enhancers);
  persistStore(store, { enhancers }, onComplete);
  return store;
}
