export const NAV_HOME = 'NAV_HOME';
export const NAV_LOGIN = 'NAV_LOGIN';
export const NAV_VENDOR_DETAIL = 'NAV_VENDOR_DETAIL';
export const NAV_VENDOR_INFO = 'NAV_VENDOR_INFO';

export const AUTH_RESET_BY_KEY = "AUTH_RESET_BY_KEY";
export const CHANGE_PHONE = "CHANGE_PHONE";
export const REOTP_CODE_REQUEST = 'REOTP_CODE_REQUEST';
export const OTP_CODE_REQUEST = 'OTP_CODE_REQUEST';
export const OTP_CODE_SUCCESS = 'OTP_CODE_SUCCESS';
export const OTP_CODE_FAILURE = 'OTP_CODE_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

//app
export const CHANGE_STATE_ISLOADING = 'CHANGE_STATE_ISLOADING';
export const CHANGE_STATE_ERROR = 'CHANGE_STATE_ERROR';

//Vendor

export const VENDORS_GETLIST_RESET_BY_KEY = 'VENDORS_GETLIST_RESET_BY_KEY';
export const VENDORS_GETLIST_REFRESHING = 'VENDORS_GETLIST_REFRESHING';
export const VENDORS_GETLIST_REQUEST = 'VENDORS_GETLIST_REQUEST';
export const VENDORS_GETLIST_SUCCESS = 'VENDORS_GETLIST_SUCCESS';
export const VENDORS_GETLIST_FAILURE = 'VENDORS_GETLIST_FAILURE';

export const VENDORS_DETAIL_RESET_BY_KEY = 'VENDORS_DETAIL_RESET_BY_KEY';
export const VENDORS_DETAIL_REFRESHING = 'VENDORS_DETAIL_REFRESHING';
export const VENDORS_DETAIL_REQUEST = 'VENDORS_DETAIL_REQUEST';
export const VENDORS_DETAIL_SUCCESS = 'VENDORS_DETAIL_SUCCESS';
export const VENDORS_DETAIL_FAILURE = 'VENDORS_DETAIL_FAILURE';


export const VENDORS_HOME_RESET_BY_KEY = 'VENDORS_HOME_RESET_BY_KEY';
export const VENDORS_HOME_REQUEST = 'VENDORS_HOME_REQUEST';
export const VENDORS_HOME_SUCCESS = 'VENDORS_HOME_SUCCESS';
export const VENDORS_HOME_FAILURE = 'VENDORS_HOME_FAILURE';


//Request


export const R_REQUEST_CLOSE_REQUEST = 'R_REQUEST_CLOSE_REQUEST';
export const R_REQUEST_CLOSE_SUCCESS = 'R_REQUEST_CLOSE_SUCCESS';
export const R_REQUEST_CLOSE_FAILURE = 'R_REQUEST_CLOSE_FAILURE';

export const R_REQUESTS_GETLIST_RESET_BY_KEY = 'R_REQUESTS_GETLIST_RESET_BY_KEY';
export const R_REQUESTS_GETLIST_REFRESHING = 'R_REQUESTS_GETLIST_REFRESHING';
export const R_REQUESTS_GETLIST_REQUEST = 'R_REQUESTS_GETLIST_REQUEST';
export const R_REQUESTS_GETLIST_SUCCESS = 'R_REQUESTS_GETLIST_SUCCESS';
export const R_REQUESTS_GETLIST_FAILURE = 'R_REQUESTS_GETLIST_FAILURE';

export const FEE_GETLIST_RESET_BY_KEY = 'FEE_GETLIST_RESET_BY_KEY';
export const FEE_GETLIST_REFRESHING = 'FEE_GETLIST_REFRESHING';
export const FEE_GETLIST_REQUEST = 'FEE_GETLIST_REQUEST';
export const FEE_GETLIST_SUCCESS = 'FEE_GETLIST_SUCCESS';
export const FEE_GETLIST_FAILURE = 'FEE_GETLIST_FAILURE';

export const FEE_DETAIL_RESET_BY_KEY = 'FEE_DETAIL_RESET_BY_KEY';
export const FEE_DETAIL_REFRESHING = 'FEE_DETAIL_REFRESHING';
export const FEE_DETAIL_REQUEST = 'FEE_DETAIL_REQUEST';
export const FEE_DETAIL_SUCCESS = 'FEE_DETAIL_SUCCESS';
export const FEE_DETAIL_FAILURE = 'FEE_DETAIL_FAILURE';

export const VENDOR_REQUESTS_GETLIST_RESET_BY_KEY = 'VENDOR_REQUESTS_GETLIST_RESET_BY_KEY';
export const VENDOR_REQUESTS_GETLIST_REFRESHING = 'VENDOR_REQUESTS_GETLIST_REFRESHING';
export const VENDOR_REQUESTS_GETLIST_REQUEST = 'VENDOR_REQUESTS_GETLIST_REQUEST';
export const VENDOR_REQUESTS_GETLIST_SUCCESS = 'VENDOR_REQUESTS_GETLIST_SUCCESS';
export const VENDOR_REQUESTS_GETLIST_FAILURE = 'VENDOR_REQUESTS_GETLIST_FAILURE';

export const VENDOR_NEWS_GETLIST_RESET_BY_KEY = 'VENDOR_NEWS_GETLIST_RESET_BY_KEY';
export const VENDOR_NEWS_GETLIST_REFRESHING = 'VENDOR_NEWS_GETLIST_REFRESHING';
export const VENDOR_NEWS_GETLIST_REQUEST = 'VENDOR_NEWS_GETLIST_REQUEST';
export const VENDOR_NEWS_GETLIST_SUCCESS = 'VENDOR_NEWS_GETLIST_SUCCESS';
export const VENDOR_NEWS_GETLIST_FAILURE = 'VENDOR_NEWS_GETLIST_FAILURE';

export const R_REQUEST_CREATE_REQUEST = 'R_REQUEST_CREATE_REQUEST';
export const R_REQUEST_CREATE_SUCCESS = 'R_REQUEST_CREATE_SUCCESS';
export const R_REQUEST_CREATE_FAILURE = 'R_REQUEST_CREATE_FAILURE';

export const R_REQUEST_DETAIL_REQUEST = 'R_REQUEST_DETAIL_REQUEST';
export const R_REQUEST_DETAIL_SUCCESS = 'R_REQUEST_DETAIL_SUCCESS';
export const R_REQUEST_DETAIL_FAILURE = 'R_REQUEST_DETAIL_FAILURE';
export const R_REQUEST_RATE_REQUEST = 'R_REQUEST_RATE_REQUEST';
export const R_REQUEST_RATE_SUCCESS = 'R_REQUEST_RATE_SUCCESS';
export const R_REQUEST_RATE_FAILURE = 'R_REQUEST_RATE_FAILURE';
export const R_REQUEST_DETAIL_RESET_BY_KEY = 'R_REQUEST_DETAIL_RESET_BY_KEY';
export const R_REQUEST_DETAIL_REFRESHING = 'R_REQUEST_DETAIL_REFRESHING';

//News

export const NEWS_GETLIST_RESET_BY_KEY = 'NEWS_GETLIST_RESET_BY_KEY';
export const NEWS_GETLIST_REFRESHING = 'NEWS_GETLIST_REFRESHING';
export const NEWS_GETLIST_REQUEST = 'NEWS_GETLIST_REQUEST';
export const NEWS_GETLIST_SUCCESS = 'NEWS_GETLIST_SUCCESS';
export const NEWS_GETLIST_FAILURE = 'NEWS_GETLIST_FAILURE';

//Notification

export const R_NOTIFICATION_GETLIST_RESET_BY_KEY = 'R_NOTIFICATION_GETLIST_RESET_BY_KEY';
export const R_NOTIFICATION_GETLIST_REFRESHING = 'R_NOTIFICATION_GETLIST_REFRESHING';
export const R_NOTIFICATION_GETLIST_REQUEST = 'R_NOTIFICATION_GETLIST_REQUEST';
export const R_NOTIFICATION_GETLIST_SUCCESS = 'R_NOTIFICATION_GETLIST_SUCCESS';
export const R_NOTIFICATION_GETLIST_FAILURE = 'R_NOTIFICATION_GETLIST_FAILURE';

export const DEPARMENT_DETAIL_RESET_BY_KEY = 'DEPARMENT_DETAIL_RESET_BY_KEY';
export const DEPARMENT_DETAIL_REQUEST = 'DEPARMENT_DETAIL_REQUEST';
export const DEPARMENT_DETAIL_SUCCESS = 'DEPARMENT_DETAIL_SUCCESS';
export const DEPARMENT_DETAIL_FAILURE = 'DEPARMENT_DETAIL_FAILURE';
export const DEPARMENT_UPDATE_REQUEST = 'DEPARMENT_UPDATE_REQUEST';
export const DEPARMENT_UPDATE_SUCCESS = 'DEPARMENT_UPDATE_SUCCESS';
export const DEPARMENT_UPDATE_FAILURE = 'DEPARMENT_UPDATE_FAILURE';
export const DEPARMENT_ON_VALUE_CHANGE = 'DEPARMENT_ON_VALUE_CHANGE';


//Payment history
export const PAYMENTHIS_GETLIST_RESET_BY_KEY = 'PAYMENTHIS_GETLIST_RESET_BY_KEY';
export const PAYMENTHIS_GETLIST_REFRESHING = 'PAYMENTHIS_GETLIST_REFRESHING';
export const PAYMENTHIS_GETLIST_REQUEST = 'PAYMENTHIS_GETLIST_REQUEST';
export const PAYMENTHIS_GETLIST_SUCCESS = 'PAYMENTHIS_GETLIST_SUCCESS';
export const PAYMENTHIS_GETLIST_FAILURE = 'PAYMENTHIS_GETLIST_FAILURE';

//Utils
export const UTILITIES_GETLIST_RESET_BY_KEY = 'UTILITIES_GETLIST_RESET_BY_KEY';
export const UTILITIES_GETLIST_REQUEST = 'UTILITIES_GETLIST_REQUEST';
export const UTILITIES_GETLIST_SUCCESS = 'UTILITIES_GETLIST_SUCCESS';
export const UTILITIES_GETLIST_FAILURE = 'UTILITIES_GETLIST_FAILURE';
export const UTILITIES_GETLIST_REFRESHING = 'UTILITIES_GETLIST_REFRESHING';


export const UTILITIES_SERVICES_GETLIST_RESET_BY_KEY = 'UTILITIES_SERVICES_GETLIST_RESET_BY_KEY';
export const UTILITIES_SERVICES_GETLIST_REQUEST = 'UTILITIES_SERVICES_GETLIST_REQUEST';
export const UTILITIES_SERVICES_GETLIST_SUCCESS = 'UTILITIES_SERVICES_GETLIST_SUCCESS';
export const UTILITIES_SERVICES_GETLIST_FAILURE = 'UTILITIES_SERVICES_GETLIST_FAILURE';
export const UTILITIES_SERVICES_GETLIST_REFRESHING = 'UTILITIES_SERVICES_GETLIST_REFRESHING';

export const UTILITIES_SERVICES_DETAIL_RESET_BY_KEY = 'UTILITIES_SERVICES_DETAIL_RESET_BY_KEY';
export const UTILITIES_SERVICES_DETAIL_REQUEST = 'UTILITIES_SERVICES_DETAIL_REQUEST';
export const UTILITIES_SERVICES_DETAIL_SUCCESS = 'UTILITIES_SERVICES_DETAIL_SUCCESS';
export const UTILITIES_SERVICES_DETAIL_FAILURE = 'UTILITIES_SERVICES_DETAIL_FAILURE';

export const UTILITIES_SERVICES_BOOKING_REQUEST = 'UTILITIES_SERVICES_BOOKING_REQUEST';
export const UTILITIES_SERVICES_BOOKING_SUCCESS = 'UTILITIES_SERVICES_BOOKING_SUCCESS';
export const UTILITIES_SERVICES_BOOKING_FAILURE = 'UTILITIES_SERVICES_BOOKING_FAILURE';

export const UTILITIES_SERVICES_EXTENSION_GETLIST_RESET_BY_KEY = 'UTILITIES_SERVICES_EXTENSION_GETLIST_RESET_BY_KEY';
export const UTILITIES_SERVICES_EXTENSION_GETLIST_REFRESHING = 'UTILITIES_SERVICES_EXTENSION_GETLIST_REFRESHING';
export const UTILITIES_SERVICES_EXTENSION_GETLIST_REQUEST = 'UTILITIES_SERVICES_EXTENSION_GETLIST_REQUEST';
export const UTILITIES_SERVICES_EXTENSION_GETLIST_SUCCESS = 'UTILITIES_SERVICES_EXTENSION_GETLIST_SUCCESS';
export const UTILITIES_SERVICES_EXTENSION_GETLIST_FAILURE = 'UTILITIES_SERVICES_EXTENSION_GETLIST_FAILURE';

export const UTILITIES_SERVICES_EXTENSION_DETAIL_RESET_BY_KEY = 'UTILITIES_SERVICES_EXTENSION_DETAIL_RESET_BY_KEY';
export const UTILITIES_SERVICES_EXTENSION_DETAIL_REFRESHING = 'UTILITIES_SERVICES_EXTENSION_DETAIL_REFRESHING';
export const UTILITIES_SERVICES_EXTENSION_DETAIL_REQUEST = 'UTILITIES_SERVICES_EXTENSION_DETAIL_REQUEST';
export const UTILITIES_SERVICES_EXTENSION_DETAIL_SUCCESS = 'UTILITIES_SERVICES_EXTENSION_DETAIL_SUCCESS';
export const UTILITIES_SERVICES_EXTENSION_DETAIL_FAILURE = 'UTILITIES_SERVICES_EXTENSION_DETAIL_FAILURE';
export const SERVICES_EXTENSION_RATE_REQUEST = 'SERVICES_EXTENSION_RATE_REQUEST';
export const SERVICES_EXTENSION_RATE_SUCCESS = 'SERVICES_EXTENSION_RATE_SUCCESS';
export const SERVICES_EXTENSION_RATE_FAILURE = 'SERVICES_EXTENSION_RATE_FAILURE';
export const SERVICES_EXTENSION_FEEDBACK_REQUEST = 'SERVICES_EXTENSION_FEEDBACK_REQUEST';
export const SERVICES_EXTENSION_FEEDBACK_SUCCESS = 'SERVICES_EXTENSION_FEEDBACK_SUCCESS';
export const SERVICES_EXTENSION_FEEDBACK_FAILURE = 'SERVICES_EXTENSION_FEEDBACK_FAILURE';

//Service Basic
export const UTILITIES_SERVICES_BASIC_GETLIST_RESET_BY_KEY = 'UTILITIES_SERVICES_BASIC_GETLIST_RESET_BY_KEY';
export const UTILITIES_SERVICES_BASIC_GETLIST_REFRESHING = 'UTILITIES_SERVICES_BASIC_GETLIST_REFRESHING';
export const UTILITIES_SERVICES_BASIC_GETLIST_REQUEST = 'UTILITIES_SERVICES_BASIC_GETLIST_REQUEST';
export const UTILITIES_SERVICES_BASIC_GETLIST_SUCCESS = 'UTILITIES_SERVICES_BASIC_GETLIST_SUCCESS';
export const UTILITIES_SERVICES_BASIC_GETLIST_FAILURE = 'UTILITIES_SERVICES_BASIC_GETLIST_FAILURE';

export const UTILITIES_SERVICES_BASIC_DETAIL_RESET_BY_KEY = 'UTILITIES_SERVICES_BASIC_DETAIL_RESET_BY_KEY';
export const UTILITIES_SERVICES_BASIC_DETAIL_REFRESHING = 'UTILITIES_SERVICES_BASIC_DETAIL_REFRESHING';
export const UTILITIES_SERVICES_BASIC_DETAIL_REQUEST = 'UTILITIES_SERVICES_BASIC_DETAIL_REQUEST';
export const UTILITIES_SERVICES_BASIC_DETAIL_SUCCESS = 'UTILITIES_SERVICES_BASIC_DETAIL_SUCCESS';
export const UTILITIES_SERVICES_BASIC_DETAIL_FAILURE = 'UTILITIES_SERVICES_BASIC_DETAIL_FAILURE';
export const SERVICES_BASIC_FEEDBACK_REQUEST = 'SERVICES_BASIC_FEEDBACK_REQUEST';
export const SERVICES_BASIC_FEEDBACK_SUCCESS = 'SERVICES_BASIC_FEEDBACK_SUCCESS';
export const SERVICES_BASIC_FEEDBACK_FAILURE = 'SERVICES_BASIC_FEEDBACK_FAILURE';

export const UTILITIES_BASIC_DETAIL_RESET_BY_KEY = 'UTILITIES_BASIC_DETAIL_RESET_BY_KEY';
export const UTILITIES_BASIC_DETAIL_REQUEST = 'UTILITIES_BASIC_DETAIL_REQUEST';
export const UTILITIES_BASIC_DETAIL_SUCCESS = 'UTILITIES_BASIC_DETAIL_SUCCESS';
export const UTILITIES_BASIC_DETAIL_FAILURE = 'UTILITIES_BASIC_DETAIL_FAILURE';
export const UTILITIES_BASIC_DETAIL_REFRESHING = 'UTILITIES_BASIC_DETAIL_REFRESHING';

//BASIC BOOK 
export const UTILITIES_BASIC_ZONETIME_RESET_BY_KEY = 'UTILITIES_BASIC_ZONETIME_RESET_BY_KEY';
export const UTILITIES_BASIC_ZONETIME_REQUEST = 'UTILITIES_BASIC_ZONETIME_REQUEST';
export const UTILITIES_BASIC_ZONETIME_SUCCESS = 'UTILITIES_BASIC_ZONETIME_SUCCESS';
export const UTILITIES_BASIC_ZONETIME_FAILURE = 'UTILITIES_BASIC_ZONETIME_FAILURE';
export const UTILITIES_BASIC_BOOKING_ON_VALUE_CHANGE = 'UTILITIES_BASIC_BOOKING_ON_VALUE_CHANGE';

export const UTILITIES_BASIC_BOOKING_REQUEST = 'UTILITIES_BASIC_BOOKING_REQUEST';
export const UTILITIES_BASIC_BOOKING_SUCCESS = 'UTILITIES_BASIC_BOOKING_SUCCESS';
export const UTILITIES_BASIC_BOOKING_FAILURE = 'UTILITIES_BASIC_BOOKING_FAILURE';

export const BADGE_NOTIFY_R_REQUEST = 'BADGE_NOTIFY_R_REQUEST';
export const BADGE_NOTIFY_R_SUCCESS = 'BADGE_NOTIFY_R_SUCCESS';
export const BADGE_NOTIFY_R_FAILURE = 'BADGE_NOTIFY_R_FAILURE';
export const BADGE_PAYMENT_R_SUCCESS = 'BADGE_PAYMENT_R_SUCCESS';
export const BADGE_REQUEST_R_SUCCESS = 'BADGE_REQUEST_R_SUCCESS';

export const REQUEST_GET_TOTAL_STATUS_REQUEST = 'REQUEST_GET_TOTAL_STATUS_REQUEST';
export const REQUEST_GET_TOTAL_STATUS_SUCCESS = 'REQUEST_GET_TOTAL_STATUS_SUCCESS';
export const REQUEST_GET_TOTAL_STATUS_FAILURE = 'REQUEST_GET_TOTAL_STATUS_FAILURE';

export const R_NEWS_GETLIST_RESET_BY_KEY = 'R_NEWS_GETLIST_RESET_BY_KEY';
export const R_NEWS_GETLIST_REFRESHING = 'R_NEWS_GETLIST_REFRESHING';
export const R_NEWS_GETLIST_REQUEST = 'R_NEWS_GETLIST_REQUEST';
export const R_NEWS_GETLIST_SUCCESS = 'R_NEWS_GETLIST_SUCCESS';
export const R_NEWS_GETLIST_FAILURE = 'R_NEWS_GETLIST_FAILURE';

export const HANDOVER_SCHEDULE_SUCCESS = 'HANDOVER_SCHEDULE_SUCCESS';
export const HANDOVER_SCHEDULE_REQUEST = 'HANDOVER_SCHEDULE_REQUEST';
export const HANDOVER_SCHEDULE_FAILURE = 'HANDOVER_SCHEDULE_FAILURE';
export const HANDOVER_SCHEDULE_REFRESHING = 'HANDOVER_SCHEDULE_REFRESHING';
export const HANDOVER_SCHEDULE_RESET_BY_KEY = 'HANDOVER_SCHEDULE_RESET_BY_KEY';