// ES6 module syntax
import LocalizedStrings from "react-native-localization";

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

let Strings = new LocalizedStrings({
  vi: {
    message: {
      please: "Vui lòng",
      pleaseWait: "Vui lòng chờ",
      pleaseType: "Vui lòng nhập",
      saveSuccess: "Cập nhật thành công.",
      saveError: "Đã xảy ra lỗi. Vui lòng thử lại sau, xin cảm ơn.",
      CODE_OTP_INVALID:
        "Mã xác thực không chính xác. Vui lòng thử lại, xin cảm ơn.",
      DATA_NOT_FOUND:
        "Số điện thoại chưa đăng ký. Vui lòng liên hệ Ban quản lý, xin cảm ơn.",
      INVALID_ACCESS:
        "Số điện thoại chưa đăng ký. Vui lòng liên hệ Ban quản lý, xin cảm ơn.",
      RESIDENTS_NOT_IN_THE_BUILDING:
        "Đã xảy ra lỗi. Vui lòng liên hệ Ban quản lý, xin cảm ơn.",
      PASS_INVALID: "Mật khẩu không chính xác.",
      bookSuccess: "Đặt thành công",
    },
    app: {
      placeholderSearchBar: "Tìm kiếm",
      emptyData: "Không có dữ liệu",
      error: "Lỗi kết nối",
      cancel: "Hủy",
      chose: "Chọn",
      progressing: "Đang xử lý...",
      confirm: "Xác nhận",
      description: "Diễn giải",
    },
    tabbar: {
      home: "Trang chủ",
      notification: "Thông báo",
      request: "Yêu cầu",
      more: "Thêm",
      my: "Của tôi",
      news: "Tin tức",
    },
    login: {
      logo: "MIK Home Living Excellence",
      title: "Vui lòng nhập Số điện thoại để tiếp tục",
      title2: "Quý khách vui lòng kiểm tra hộp thư SMS để nhận mã xác thực",
      phone: "Số điện thoại",
      password: "Mật khẩu",
      code: "Mã xác thực",
      button1: "Tiếp tục",
      button2: "Xác thực",
      resent: "Gửi lại mã",
      changephone: "Đổi số điện thoại",
      byOTP: "Sử dụng OTP",
      byPass: "Sử dụng mật khẩu",
      emptyPhone: "Vui lòng nhập số điện thoại đã đăng ký",
      emptyPass: "Vui lòng nhập số điện thoại hoặc mật khẩu đã đăng ký",
      emptyOtp: "Vui lòng nhập otp gửi tới số điện thoại của bạn đã đăng ký",
      button3: "Đăng ký",
      passwordRetype: "Nhập lại mật khẩu",
      label1: "Đã có tài khoản?",
      label2: "Bạn là cư dân chưa có tài khoản?",
      label3: "Đăng nhập",
      changePass: "Đổi mật khẩu",
    },
    listVendor: {
      option1: "Đã tham gia",
      option2: "Chưa tham gia",
      option3: "Tất cả",
    },
    detailVendor: {
      leave: "Rời khỏi",
      join: "Tham gia",
      more: "Thêm",
      request: "Quản lý yêu cầu",
      news: "Quản lý tin tức",
      fee: "Tra cứu phí",
      info: "Giới thiệu",
    },
    fee: {
      total: "Tổng phí dịch vụ theo tháng",
      detail: "chi tiết",
      unit: "Đơn vị tính",
      contractNo: "Số HĐ/Mã CH",
      balance: "Nợ đầu kỳ tháng",
      occursduring: "Phát sinh trong kỳ tháng",
      paid: "Đã thu",
    },
    listRequest: {
      option1: "Mới",
      option2: "Đang xử lý",
      option3: "Hoàn thành",
      option4: "Đóng",
    },
    common: {
      choose: 'Chọn',
      type: 'Nhập',
      department: 'Phòng ban',
      employee: 'Nhân viên',
      workingGroup: 'Nhóm công việc',
      group: 'Nhóm',
      priority: "Cấp độ",
      pleaseChoose: 'Vui lòng chọn',
      yesterday: 'Hôm qua',
      at: 'lúc',
      month: 'tháng',
      emergency: 'Khẩn cấp',
      normal: "Bình thường",
      low: "Thấp",
      status: 'Trạng thái',
      service: "Tiện ích",
      extension: "Dịch vụ",
    },
    request: {
      title: 'Công việc',
      mine: 'Của tôi',
      source: 'Nguồn',
      all: 'Tất cả',
      fromResidents: 'Từ cư dân',
      operatingWord: 'Từ vận hành',
      unfiltered: 'Bỏ lọc',
      filter: 'Lọc dữ liệu'
    },
    createRequest: {
      navTitle: "Tạo công việc",
      next: "Tiếp tục",
      vendor: "Gửi đến",
      department: "Nơi tiếp nhận",
      contractNo: "MÃ SỐ HĐ/CH",
      title: "Tiêu đề",
      content: "Nội dung",
      reason: "Lý do",
      phone: "Số điện thoại",
      from: "Người gửi",
      date: "Thời gian liên lạc",
      at: "Vào lúc",
      unreceived: "Chưa tiếp nhận",
      received: "Đã tiếp nhận",
      placeholderVendor: "Chọn tòa nhà",
      placeholderDepartment: "Chọn phòng ban",
      placeholderEmployee: "Chọn nhân viên",
      placeholderStatus: "Chọn trạng thái",
      placeholderGroup: "Chọn nhóm công việc",
      placeholderPriority: "Chọn cấp độ",
      contract: "Contract",
      placeholderTitle: "Nhập tiêu đề",
      placeholderContent: "Nội dung yêu cầu",
      placeholderReason: "Lý do đổi ",
      placeholderSender: "Tên người gửi",
      placeholderPhone: "Điện thoại liên hệ",
      titlePicker: "Ngày liên hệ",
      takeAPhoto: "Chụp ảnh",
      chooseAnImage: "Chọn hình ảnh",
      SelectFromGallery: "Chọn ảnh từ thư viện",
      cancel: "Huỷ",
      access: "Cấp quyền truy cập",
      access2: "Cho phép ứng dụng chụp ảnh và chọn từ thư viên ảnh",
      retry: " Thử lại",
      allow: " Cho phép",
      textPhoto: "Nhấn vào để tải ảnh",
      complete: "Hoàn tất",
      addPhoto: "Thêm ảnh",
    },
    detailRequest: {
      tabContent: "Nội dung",
      tabHistory: "Lịch sử",
      tabContact: "Liên hệ",
      butonText: "Phản hồi",
      imagesCustomer: "Ảnh đã gửi",
      imagesAdmin: "Ảnh bql phản hồi",
      forward: "Chuyển tiếp",
      inform: "Tiếp nhận",
      complete: "Hoàn thành",
      imageEmployee: "Ảnh nhân viên up"
    },
    forwardRequest: {
      group: "nhóm xử lý",
      isChoseemployee: "chọn nhân viên cụ thể",
      employee: "nhân viên",
      phoneemployee: "số đt nhân viên",
      resion: "lý do chuyển tiếp",
      selectVendor: "Chọn nhà cung cấp",
      unSelect: "chưa chọn",
      inputPhonenumber: "Nhập số điện thoại",
    },
    setting: {
      notification: "thông báo",
      ring: "Đỗ chuông",
      vibrate: "Rung",
      message: "Khi có thông báo mới",
      language: "Ngôn ngữ",
      towerAddress: "Địa chỉ",
      service: "Tiện ích",
      extension: "Dịch vụ",
      logout: "Đăng xuất",
      changeTypeUser: "Đổi vai trò người dùng",
      survey: "Phiếu khảo sát",
      workingGroup: 'Nhóm công việc',
      staff: 'Nhân viên',
      department: 'Phòng ban',
      general: 'Tổng hợp',
      system: 'Hệ thống',
      systemStatistics: 'Thống kê hệ thống',
      request: 'Phản ánh',
      mine: 'Của tôi',
      unfiltered: 'Bỏ lọc',
      filter: 'Lọc dữ liệu',
      group: 'nhóm',

    },
    profile: {
      setting: "Cài đặt",
      logout: "Đăng xuất",
      changeTypeUser: "Đổi vai trò người dùng",
      questionChangeUser: "Bạn có chắc chắn muốn đổi sang tài khoản cư dân?",
      language: "Ngôn ngữ",

    },
    serviceBasicBooking: {
      position: "Khu vực",
      deposit: "Tiền cọc",
      amountPeople: "Số lượng người",
      dateBook: "Ngày đặt",
      dateCreate: "Ngày tạo",
      time: "Suất đặt",
      message: "Lời nhắn",
      messagePlaceholder: "Nhập lời nhắn",
      messageChoice: "Vui lòng chọn SUẤT ĐẶT, xin cảm ơn.",
    },
    serviceExtension: {
      amount: "Số lượng",
      dateBook: "Ngày đặt",
      dateCreate: "Ngày tạo",
      message: "Lời nhắn",
      totalPrice: "Tổng tiền",
      price: "Đơn giá",
    },
    checklist: {
      download: "Tải",
      unDownload: "Xoá tải",
    },
    home: {
      titleNews1: "Tin mới",
      titleNews2: "Bài viết khác",
      electric: "Điện",
      water: "Nước",
      gas: "Gas",
      shift: "Ca trực",
      checkList: "Checklist",
      proposalForm: "Phiếu đề xuất",
      checkingDaily: "Kiểm tra định kỳ",
      internalHandover: "Bàn giao nội bộ",
      customerHandover: "Bàn giao khách hàng",
      service: "Tiện ích",
      extension: "Dịch vụ",
      functionalCategories: "Danh mục chức năng",
    },
    statistical: {
      generalStatistics: 'Thống kê tổng hợp',
      departmentalStatistics: 'Thống kê phòng ban',
      employeeStatistics: 'Thống kê nhân viên',
      workGroupStatistics: 'Thống kê nhóm công việc',
      date: 'Ngày',
      week: 'Tuần',
      month: 'Tháng',
      from: 'Từ',
      to: 'đến',
      averageHandlingTime: "Thời gian xử lý trung bình",
      averageRating: 'Điểm đánh giá trung bình',
      time: 'Thời gian',
      custom: 'Tuỳ chỉnh',
      close: "Đóng",
      year: 'Năm',
      quarter: 'Quý'
    },
    survey: {
      navTitle: 'Phiếu khảo sát',
      listOfAnswers: 'Danh sách câu trả lời',
      selectToSeeDetails: 'Chọn để xem chi tiết'
    },
    notifycation: {
      navTitle: "Thông báo",
      source: 'Nguồn',
      unfiltered: 'Bỏ lọc',
      filter: 'Lọc dữ liệu',
      group: 'nhóm',
      all: 'Tất cả',
      request: 'Công việc',
      service: "Tiện ích",
      extension: "Dịch vụ",
      suggestedRepair: 'Đề xuất sửa chữa'
    },
    electric: {
      navTitleElectric: 'Điện',
      navTitleWater: 'Nước',
      navTitleGas: 'Gas',
      block: "Khối nhà",
      floor: 'Tầng',
      period: 'Kỳ',
      unfiltered: 'Bỏ lọc',
      filter: 'Lọc dữ liệu',
      noIndexYet: "Chưa ghi chỉ số",
      writeIndex: "Ghi chỉ số",
      newIndex: "Chỉ số mới",
      indexImage: "Hình ảnh chỉ số",
      VATrate: "Tỉ lệ VAT",
      note: "Ghi chú",
      oldIndex: 'Chỉ số cũ',
      amountOfConsumption: 'Số tiêu thụ',
      paymentPeriod: 'Kỳ thanh toán',
      dateOfPayment: 'Ngày thanh toán',
      notificationDate: 'Ngày thông báo',
      amountOfPeopleGetEndow: 'Số người ưu đãi', //Number of people in preferential treatment
      m3person: "Số M3/người",
      rateBVMT: "Tỷ lệ phí BVMT",//Rate of environmental protection fee
      unit: "Đơn vị tính",
      exchangeRate: "Tỷ giá QĐ",
      time: 'Thời gian',
      month: 'Tháng',
      year: 'Năm',
      totalAmount: 'Tổng tiền',
      mesWanning: 'Cảnh báo số liệu bất thường, bạn có muốn tiếp tục',
      continue: 'Tiếp tục',
      cancel: 'Huỷ'
    },
    handover: {
      navTitleInternal: 'Bàn giao nội bộ', //internal handover
      today: 'Hôm nay',
      yesterday: 'Hôm qua',
      thisMonth: 'Tháng này',
      thisYear: 'Năm này',
      time: 'Thời gian',
      status1: 'Chờ bàn giao nội bộ',
      status2: 'Chuyển nhà thầu xử lý',
      status3: 'Chờ bàn giao khách hàng',
      status4: 'Nhà thầu đã sửa chữa xong',
      status5: 'Tất cả',
      navTitleCustomer: 'Bàn giao khách hàng', //Customer handing over
      status6: 'Chờ bàn giao khách hàng',
      status7: 'Bàn giao không thành công (Có lỗi)',
      status8: 'Bàn giao thành công có lỗi',
      status9: 'Đã bàn giao thành công',
      status10: 'Nhà thầu đã sửa chữa xong',
      status11: 'Mặc nhiên bàn giao',
      status12: 'Bàn giao nội bộ thành công (có lỗi)',
      status13: 'Bàn giao nội bộ thành công',
      navTitleDetail: 'Danh mục tài sản',
      describe: 'Mô tả',
      cancel: 'Huỷ',
      ok: 'Thực hiện',
      add: 'Thêm',
      nameTestItem: 'Hạng mục kiểm tra',
      apartment: 'Mặt bằng',
      shift: 'Ca trực',
      handover: 'Bàn giao',
      failed: 'Không đạt',
      complete: 'Đạt',
      note: 'Ghi chú',
      notify: 'Thông báo',
      mesDeleteImage: "Bạn có chắc chắn muốn xoá", // Are you sure you want to delete,
      mesTimeUpdate: 'Cập nhật lại thời gia dự kiến hoàn thành'

    }
  },
  en: {
    home: {
      titleNews1: "News",
      titleNews2: "More posts",
      electric: "Electric",
      water: "Water",
      gas: "Gas",
      shift: "Shift",
      checkList: "Checklist",
      proposalForm: "Proposal Form",
      checkingDaily: "Checking Daily",
      internalHandover: "Internal Handover",
      customerHandover: "Customer Handover",
      service: "Service",
      extension: "Extension",
      functionalCategories: "Functional categories",
    },
    message: {
      please: "Please",
      pleaseWait: "Please wait",
      pleaseType: "Please typing",
      saveSuccess: "Updated successfull.",
      saveError: "Error! An error occurred. Please try again later.",
      CODE_OTP_INVALID:
        "Incorrect authentication code. Please try again, thanks.",
      DATA_NOT_FOUND:
        "Unregistered phone number. Please contact the management, thank you.",
      INVALID_ACCESS:
        "Unregistered phone number. Please contact the management, thank you.",
      RESIDENTS_NOT_IN_THE_BUILDING:
        "Error! An error occurred. Please contact the management, thank you.",
      PASS_INVALID: "Incorrect password.",
      bookSuccess: "Booking succesfully",
    },
    app: {
      placeholderSearchBar: "Search",
      emptyData: "Empty Data",
      error: "Conneting failure",
      cancel: "Cancel",
      chose: "Confirm",
      progressing: "Progressing...",
      confirm: "Confirm",
      description: "Description",
    },
    tabbar: {
      home: "Home",
      notification: "Notification",
      request: "Reuqest",
      more: "More",
      my: "My",
      news: "News",
    },
    login: {
      logo: "MIK Home Living Excellence",
      title: "Please enter your Phone number to continue",
      title2: "Please check your SMS box to recive verify code",
      phone: "Phone number",
      password: "Password",
      code: "VerifyCode",
      button1: "Continue",
      button2: "Verify",
      resent: "Resent Code",
      changephone: "Change Phone Number",
      byOTP: "Use OTP",
      byPass: "Use password",
      emptyPhone: "Please enter your registered phone number",
      emptyPass: "Please enter your registered phone number or password",
      emptyOtp: "Please enter OTP",
      button3: "Sign up",
      passwordRetype: "Retype password",
      label1: "Had an account",
      label2: "Don't have an account",
      label3: "Login",
      changePass: "Change password",
    },
    listVendor: {
      option1: "Joined",
      option2: "Not Join",
      option3: "All",
    },
    detailVendor: {
      leave: "Leave",
      join: "Join",
      more: "More",
      request: "Request Management",
      news: "News Management",
      fee: "Look up fees",
      info: "About",
    },
    fee: {
      total: "Total service fee by month",
      detail: "detail",
      unit: "Unit",
      contractNo: "Contract No.",
      balance: "Opening Balance",
      occursduring: "Occurs during the month",
      paid: "Paid",
    },
    listRequest: {
      option1: "New",
      option2: "Progressing",
      option3: "Complete",
      option4: "Close",
    },
    common: {
      choose: 'Choose',
      type: 'Type',
      department: 'Department',
      employee: 'Employee',
      workingGroup: 'Working Group',
      group: 'Group',
      priority: "Priority",
      pleaseChoose: 'Please choose',
      yesterday: 'Yesterday',
      at: 'at',
      month: 'month',
      emergency: 'Emergency',
      normal: "Normal",
      low: "Low",
      status: "Status",
      service: "Service",
      extension: "Extension",
    },
    request: {
      title: 'Request',
      mine: 'Mine',
      source: 'Source',
      all: 'All',
      fromResidents: 'From Residents',
      operatingWord: 'Operating Word',
      unfiltered: 'Unfiltered',
      filter: 'Filter'
    },
    createRequest: {
      navTitle: "Compose Request",
      next: "Next",
      vendor: "Send to",
      department: "Recipient",
      contractNo: "Contract no",
      title: "Title",
      content: "Content",
      reason: "Reason",
      phone: "Phone",
      from: "Sender",
      date: "Contact time",
      at: "At",
      unreceived: "Not received",
      received: "Received",
      placeholderVendor: "Select tower",
      placeholderDepartment: "Select the reception board",
      placeholderEmployee: "Select Employee",
      placeholderStatus: "Select Status",
      placeholderGroup: "Select group",
      placeholderPriority: "Select priority",

      contract: "Contract",
      placeholderTitle: "Enter title",
      placeholderContent: "Content Request",
      placeholderReason: "Reason Request",
      placeholderSender: "Contact name",
      placeholderPhone: "Contact phone",
      titlePicker: "Date Contact",
      takeAPhoto: "Take a photo",
      chooseAnImage: "Choose An Image",
      SelectFromGallery: "Select photo from gallery",
      cancel: "Cancel",
      access: "Grant of access",
      access2: "Allows the app to take pictures and choose from photo gallery",
      retry: "Retry",
      allow: "Allow",
      textPhoto: "Click to download the photo",
      complete: "Completed",
      addPhoto: "Add photo",
    },
    detailRequest: {
      tabContent: "Content",
      tabHistory: "History",
      tabContact: "Contact",
      butonText: "Feedback",
      imagesCustomer: "Photos has been sent",
      imagesAdmin: "Photos feedback",
      forward: "Forward",
      inform: "Inform",
      complete: "Complete",
      imageEmployee: "Image from employee"
    },
    forwardRequest: {
      group: "Group",
      isChoseemployee: "chọn nhân viên cụ thể",
      employee: "Employee",
      phoneemployee: "Phone number",
      resion: "Resion",
      selectVendor: "Select Vendor",
      unSelect: "UnSelect",
      inputPhonenumber: "Enter Phone Number",
    },
    setting: {
      notification: "notification",
      ring: "Ringing",
      vibrate: "Vibrate",
      message: "When receive new notification",
      language: "Language",
      towerAddress: "Address",
      service: "Service",
      extension: "Extension",
      logout: "Logout",
      changeTypeUser: "Change user roles",
      survey: "Survey",
      workingGroup: 'Working group',
      staff: 'Employee',
      department: 'Department',
      general: 'General',
      system: 'System',
      systemStatistics: 'System statistics',
      request: 'Request',
      mine: 'Mine'
    },
    profile: {
      setting: "Setting",
      logout: "Logout",
      changeTypeUser: "Change user roles",
      questionChangeUser:
        "Are you sure you want to switch to an resident account?",
    },
    serviceBasicBooking: {
      position: "Position",
      deposit: "Deposit",
      amountPeople: "Amount people",
      dateBook: "Date book",
      dateCreate: "Date create",
      time: "Time",
      message: "Message",
      messagePlaceholder: "Type message",
      messageChoice: "Please select [TIME], thank you.",
    },
    serviceExtension: {
      amount: "Amount",
      dateBook: "Date book",
      dateCreate: "Date create",
      message: "Message",
      totalPrice: "Total",
      price: "Price",
    },
    checklist: {
      download: "Download",
      unDownload: "Unload",
    },
    statistical: {
      generalStatistics: 'General statistics',
      departmentalStatistics: 'Departmental statistics',
      employeeStatistics: 'Employee statistics',
      workGroupStatistics: 'WorkGroup statistics',
      date: 'Date',
      week: 'Week',
      month: 'Month',
      from: 'From',
      to: 'to',
      averageHandlingTime: "Average handling time",
      averageRating: 'Average rating',
      time: 'Time',
      custom: 'Custom',
      close: "Close",
      year: 'Year',
      quarter: 'Quarter'
    },
    survey: {
      navTitle: 'Survey',
      listOfAnswers: 'List of answers',
      selectToSeeDetails: 'Select to see details'
    },
    notifycation: {
      navTitle: "Notifycation",
      source: 'Source',
      unfiltered: 'Unfiltered',
      filter: 'Filter',
      group: 'Group',
      all: 'All',
      request: 'Request',
      service: "Service",
      extension: "Extension",
      suggestedRepair: 'Suggested Repair'
    },

    electric: {
      navTitleElectric: 'Electric',
      navTitleWater: 'Water',
      navTitleGas: 'Gas',
      block: "Block",
      floor: 'Floor',
      period: 'Period',
      unfiltered: 'Unfiltered',
      filter: 'Filter',
      noIndexYet: "No index yet",
      writeIndex: "Write index",
      newIndex: "New index",
      indexImage: "Index image",
      VATrate: "VAT rate",
      note: "Note",
      oldIndex: 'Old index',
      amountOfConsumption: 'Amount consumption',
      paymentPeriod: 'Payment period',
      dateOfPayment: 'Date payment',
      notificationDate: 'Date notification',
      amountOfPeopleGetEndow: 'People get endow',
      m3person: "M3/person",
      rateBVMT: "Rate environmental protection fee",//Rate of environmental protection fee
      unit: "Unit",
      exchangeRate: "Eexchange rate",
      time: 'Time',
      month: 'Month',
      year: 'Year',
      totalAmount: 'Total amount',
      mesWanning: 'Abnormal data alert, do you want to continue',
      continue: 'Continue',
      cancel: 'Cancel'
    },
    handover: {
      navTitleInternal: 'Internal handover',
      today: 'Today',
      yesterday: 'Yesterday',
      thisMonth: 'This month',
      thisYear: 'This year',
      time: 'Time',
      status1: 'Waiting for internal handover',
      status2: 'Transfer to a handling contractor',
      status3: 'Waiting for customer handover',
      status4: 'The contractor has completed the repair',
      status5: 'All',
      navTitleCustomer: 'Customer handing over',
      status6: 'Waiting for customer handover',
      status7: 'Handover Failed (With Error)',
      status8: 'Successful handover with error',
      status9: 'Successfully handed over',
      status10: 'The contractor has completed the repair',
      status11: 'By default, handing over',
      status12: 'Internal handover successful (with error)',
      status13: 'Successful internal handover',
      navTitleDetail: 'Property List',
      describe: 'Describe',
      cancel: 'Cancel',
      ok: 'Ok',
      add: 'Add',
      nameTestItem: 'Name of test item',
      apartment: 'Apartment',
      shift: 'Shift',
      handover: 'Handover',
      failed: 'Failed',
      complete: 'Complete',
      note: 'Note',
      notify: 'Notify',
      mesDeleteImage: 'Are you sure you want to delete',
      mesTimeUpdate: 'Update estimated completion time'
    }
  },
});

module.exports = Strings;
